services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Se você precisar de algo explícito
    App\Mapper\CarMapper:
        autowire: true

    App\Application\UseCase\CreateCarUseCaseInterface:
        alias: App\Application\UseCase\CreateCarUseCase

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
