services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Se você precisar de algo explícito
    App\Mapper\CarMapper:
        autowire: true

    App\Domain\Repository\CarRepositoryInterface:
        alias: App\Infrastructure\Repository\CarRepository

    App\Application\UseCase\Car\CreateCar\CreateCarUseCaseInterface:
        alias: App\Application\UseCase\Car\CreateCar\CreateCarUseCase

    App\Application\UseCase\Car\DeleteCar\DeleteCarUseCaseInterface:
        alias: App\Application\UseCase\Car\DeleteCar\DeleteCarUseCase

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
